#' learn_interface UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd
#'
#' @importFrom shiny NS tagList
mod_learn_interface_ui <- function(id){
  ns <- NS(id)
  tagList(
    fluidRow(
      column(width = 6, offset = 3,
        tags$br(),
        tags$h3("Workflow"),
        tags$p("The interface implements a complete workflow of statistical analyses, from data description, model fitting, diagnostics, to result presentation."),
        tags$ul(
          tags$li("First, the interface reads and displays the input data."),
          tags$li("Second, it presents descriptive statistics of the patient records and geographic areas, where examples of raw data are also displayed."),
          tags$li("Third, users can specify and fit different models with various choices of covariates and fixed/varying effects. The model fitting is via Bayesian computation with Markov chain Monte Carlo algorithms in Stan. Model summaries are shown."),
          tags$li("Fourth, the interface shows a comparison between different models and presents their diagnostics results."),
          tags$li("Finally, interface graphs demonstrate the estimated infection prevalence over time for the targeted population and demographic and geographic subpopulations, for the selected model."),
        ),
        tags$h3("Uploading Data"),
        tags$p("The interface expect the input data to be in either of the following forms: \"individual cells\" in which each row contains information about an individual person and \"aggregated cells\" which contains the population count for each unique combination of relevant geographic-demographic factors. The latter is preferred as it offers computational advantages over its counterpart. The statistical models generated by the interface requires categorical quantities. In the future, users will be able to specify the categories to convert raw values into, but the interface currently expects the following grouping in the input data (The values in parentheses are the corresponding values expected in the input data)."),
        tags$h5("Cross-sectional Data"),
        tags$ul(
          tags$li("Sex: male, female"),
          tags$li("Race: Black, White, Hispanic, other"),
          tags$li("Age (in years): 18-29, 30-39, 40-49, 50-59, 60-69, 70+"),
          tags$li("Education level: below high school (no hs), high school (hs), some college, 4-year college, post-grad"),
          tags$li("State: each state is treated as a category. Full names, abbreviations and FIPS codes are accepted.")
        ),
        tags$h5("Spatio-temporal Data"),
        tags$ul(
          tags$li("Sex: male, female"),
          tags$li("Race: Black, White, other"),
          tags$li("Age (in years): 0-17, 18-34, 35-64, 65-74, 75+"),
          tags$li("ZIP code: each ZIP code is treated as a category"),
          tags$li("Week index: test result dates are grouped into weeks with index 1 assigned to the earliest week in the data. An optional column containing the date of the first day of each week can be included for visualization purposes. Currently, the only accepted format is yyyy-mm-dd.")
        ),
        tags$p("Users can manually aggregate their raw data if the interface cannot preprocess it or if they want more control over the process. Users familiar with R can download the preprocessing code below and modifies it as needed. The preprocessed or aggregated data must have the categorical values as described above in the right format or it will not be accepted. It also must have the right column names (see table below) as the interface uses one to extract data from the input table but it can automatically fix minor deviations such as letter case."),
        tags$p("Below is a simulated dataset that exemplifies the expected aggregated data input."),
        tabsetPanel(
          tabPanel("Spatio-temporal",
            tags$div(class = "pad_top",
              DT::dataTableOutput(outputId = ns("example_st"))
            ),
            tags$div(
              class = "interface_buttons",
              downloadButton(
                outputId = ns("save_code_st"),
                label = "Preprocessing code"
              ),
              downloadButton(
                outputId = ns("save_ex_st"),
                label = "Example data"
              ),
              downloadButton(
                outputId = ns("save_week_table"),
                label = "Week conversion table"
              )
            )
          ),
          tabPanel("Cross-sectional",
            tags$div(class = "pad_top",
              DT::dataTableOutput(outputId = ns("example_cs"))
            ),
            tags$div(
              class = "interface_buttons",
              downloadButton(
                outputId = ns("save_code_cs"),
                label = "Preprocessing code"
              ),
              downloadButton(
                outputId = ns("save_ex_w_state"),
                label = "Example data (with states)"
              ),
              downloadButton(
                outputId = ns("save_ex_wo_state"),
                label = "Example data (without states)"
              )
            )
          )
        ),
        tags$h3("Model Selection"),
        tags$p("The interface allows users to select predictors and their potential two-way interactions to be included in the model and introduce prior distributions to model parameters. The predictors can include individual-level and geographic-area-level measures."),
        tags$p("The interface treats the interaction terms that involve nominal measures with more than two categories as varying effects. The model assumes varying effects follow a normal distribution with an unknown standard deviation. The Bayesian framework assigns the following prior distributions by default as below:"),
        tags$ul(
          tags$li("Overall intercept: ", withMathJax("\\(normal(0, 3)\\)")),
          tags$li("Coefficient: ", withMathJax("\\(normal(0, 3)\\)")),
          tags$li("Standard deviation: ", withMathJax("\\(normal_+(0, 3)\\)"))
        ),
        withMathJax("where \\(normal(0, 3)\\) is a normal distribution with mean 0 and standard deviation of 3, and \\(normal_+(0, 3)\\) is a normal distribution with mean 0 and standard deviation of 3 restricted to positive values."), tags$br(),
        tags$p("The prior specification can be modified by users. The interface currently accepts the following distributions:"),
        tags$ul(
          tags$li(tags$code("normal(mu, sigma)")),
          tags$li(tags$code("student_t(nu, mu, sigma)")),
          tags$li(tags$code("structured"))
        ),
        tags$p("The syntax imitates the ", tags$a("distribution statement", href = "https://mc-stan.org/docs/functions-reference/unbounded_continuous_distributions.html", target = "_blank"), " in Stan. In addition to the standard distributions, we provide the structured prior distribution developed by ", tags$a("Si et al. (2020)", href = "https://arxiv.org/abs/1707.08220", target = "_blank"), " three types of two-way interactions: 1)  two categorical variables (both with more than two levels), 2) one categorical variable (with more than two levels) and one binary variable and 3) one categorical variable (with more than two levels) and one continuous variable. It requires the main effect of the categorical variable with more than two levels to be included as a varying effect. Below is an example of the structured prior distribution for the two-way interaction of race and age:"),
        withMathJax("Main effect of race: \\(normal(0, \\lambda_1\\sigma_{race})\\)"), tags$br(),
        withMathJax("Main effect of age: \\(normal(0, \\lambda_1\\sigma_{age})\\)"), tags$br(),
        withMathJax("Interaction of race and age: \\(normal(0, \\lambda_1\\lambda_2\\sigma_{age}\\sigma_{race}\\))"), tags$br(),
        withMathJax("Standard deviation of main effects (\\(\\sigma_{race}, \\sigma_{age}\\)): \\(normal_+(0, 1)\\)"), tags$br(),
        withMathJax("Global scale (\\(\\lambda_1\\)): \\(cauchy_+(0, 1)\\)"), tags$br(),
        withMathJax("Local scale (\\(\\lambda_2\\)): \\(normal_+(0, 1)\\)"), tags$br(),
        withMathJax("where \\(cauchy_+(0, 1)\\) is a Cauchy distribution with mean 0 and standard deviation of 1 restricted to positive values."), tags$br(),
        tags$h3("Model Fitting"),
        tags$p("The interface relies on a Bayesian framework and implements the Markov chain Monte Carlo (MCMC) algorithm for posterior computation via Stan. The MCMC chains are run in parallel for computational efficiency, and the interface automatically uses one core for one chain. We recommend that users carefully specify the number of MCMC chains based on the available computing resources."),
        tags$p("The model details for the spatio-temporal data (accounting for outcome measurement sensitivity and specification) and the cross-sectional data are available on the ",
        actionLink(
          inputId = ns("to_mrp"),
          label = "MRP"
        ),
        " page.")
      )
    )
  )
}

#' learn_interface Server Functions
#'
#' @noRd
mod_learn_interface_server <- function(id, global){
  moduleServer( id, function(input, output, session){
    ns <- session$ns

    observeEvent(input$to_mrp, {
      updateTabsetPanel(global$session,
                        inputId = "navbar",
                        selected = "nav_learn_mrp")
    })

    output$example_cs <- DT::renderDataTable({
      read.csv(app_sys("extdata/CES_data_aggregated.csv"))
    })

    output$example_st <- DT::renderDataTable({
      read.csv(app_sys("extdata/covid_test_records_aggregated.csv"))
    })

    output$save_code_cs <- downloadHandler(
      filename = function() { "preprocess.R" },
      content = function(file) {
        readLines(app_sys("extdata/preprocess_cs.R")) |> writeLines(file)
      }
    )

    output$save_code_st <- downloadHandler(
      filename = function() { "preprocess.R" },
      content = function(file) {
        readLines(app_sys("extdata/preprocess_st.R")) |> writeLines(file)
      }
    )

    output$save_ex_w_state <- downloadHandler(
      filename = function() { "CES_data_aggregated.csv" },
      content = function(file) {
        read.csv(app_sys("extdata/CES_data_aggregated.csv")) |> readr::write_csv(file)
      }
    )

    output$save_ex_wo_state <- downloadHandler(
      filename = function() { "CES_data_aggregated_wo_state.csv" },
      content = function(file) {
        read.csv(app_sys("extdata/CES_data_aggregated_wo_state.csv")) |> readr::write_csv(file)
      }
    )

    output$save_ex_st <- downloadHandler(
      filename = function() { "covid_test_records_aggregated.csv" },
      content = function(file) {
        read.csv(app_sys("extdata/covid_test_records_aggregated.csv")) |> readr::write_csv(file)
      }
    )

    output$save_week_table <- downloadHandler(
      filename = function() { "week_conversion.csv" },
      content = function(file) {
        read.csv(app_sys("extdata/week_conversion.csv")) |> readr::write_csv(file)
      }
    )

    outputOptions(output, "example_cs", suspendWhenHidden = FALSE)
    outputOptions(output, "example_st", suspendWhenHidden = FALSE)
  })
}
