name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  check:
    name: R-CMD-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Cache R library
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Restore packages
        run: Rscript -e 'renv::restore()'

      - name: Run R CMD check
        run: R CMD check --no-manual --as-cran .

      #- name: Lint with lintr   # optional
      #  run: Rscript -e 'lintr::lint_package()'

  coverage:
    name: test-coverage
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Cache R library
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Restore packages
        run: Rscript -e 'renv::restore()'

      - name: Run tests and upload coverage
        run: Rscript -e 'covr::codecov()'
