name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  check:
    name: R-CMD-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglpk-dev

      - name: Cache R library
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Restore packages
        run: Rscript -e 'renv::restore()'

      - name: Install cmdstan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(cores = 2)
        shell: Rscript {0}

      - name: Install covr
        run: Rscript -e 'install.packages("covr")'

      - name: Run R CMD check
        run: |
          R CMD check --no-manual --as-cran .



  coverage:
    name: test-coverage
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglpk-dev

      - name: Cache R library
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Restore packages
        run: Rscript -e 'renv::restore()'

      - name: Install cmdstan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(cores = 2)
        shell: Rscript {0}

      - name: Install covr
        run: Rscript -e 'install.packages("covr")'

      - name: Run tests and upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          Rscript -e 'covr::codecov(token = Sys.getenv("CODECOV_TOKEN"))'
