name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]

env:
  R_CONFIG_ACTIVE: shinyapps

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Restore packages
        run: Rscript -e 'renv::restore()'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglpk-dev \
            libcurl4-openssl-dev \
            pkg-config

      - name: Ensure rsconnect is available  
        run: Rscript -e 'if (!requireNamespace("rsconnect", quietly=TRUE)) install.packages("rsconnect")'

      - name: Authenticate with shinyapps.io  
        run: |
          Rscript -e "rsconnect::setAccountInfo(
            name   = Sys.getenv('SHINYAPPS_ACCOUNT'),
            token  = Sys.getenv('SHINYAPPS_TOKEN'),
            secret = Sys.getenv('SHINYAPPS_SECRET')
          )"  # The rsconnect package sends your app bundle up :contentReference[oaicite:1]{index=1}

      - name: Deploy app  
        run: |
          Rscript -e "rsconnect::deployApp(
            appDir  = '.',
            appName = 'shinymrp',
            server  = 'shinyapps.io'
          )"
