name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]

env:
  R_CONFIG_ACTIVE: shinyapps

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Restore packages
        run: Rscript -e 'renv::restore()'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglpk-dev

      - name: Deploy to shinyapps.io
        uses: rstudio/rsconnect-action@v1
        with:
          server-url: https://shinyapps.io
          account: ${{ secrets.SHINYAPPS_ACCOUNT }}
          token:   ${{ secrets.SHINYAPPS_TOKEN }}
          secret:  ${{ secrets.SHINYAPPS_SECRET }}
          app-dir: .          
          app-name: shinymrp
