name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Publish to shinyapps.io
    runs-on: ubuntu-latest
    env:
      R_CONFIG_ACTIVE: shinyapps          # must match a section in your config.yml
      SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
      SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Restore packages
        run: Rscript -e 'renv::restore()'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglpk-dev \                  # existing dep
            libcurl4-openssl-dev \         # for curl
            pkg-config \                   # .pc lookup
            libfontconfig1-dev \           # for systemfonts
            libfreetype6-dev               # for systemfonts

      - name: Ensure rsconnect is available
        run: Rscript -e 'if (!requireNamespace("rsconnect", quietly=TRUE)) install.packages("rsconnect")'

      - name: Authenticate with shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(
            name   = Sys.getenv('SHINYAPPS_ACCOUNT'),
            token  = Sys.getenv('SHINYAPPS_TOKEN'),
            secret = Sys.getenv('SHINYAPPS_SECRET')
          )"

      - name: Deploy app
        run: |
          Rscript -e "rsconnect::deployApp(
            appDir  = '.',
            appName = 'shinymrp',
            server  = 'shinyapps.io'
          )"
