name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Publish to shinyapps.io
    runs-on: ubuntu-latest
    env:
      R_CONFIG_ACTIVE: shinyapps
      SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
      SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            pkg-config \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libcairo2-dev \
            libxt-dev \
            libpng-dev \
            libjpeg-dev \
            libtiff5-dev \
            zlib1g-dev \
            libbz2-dev \
            liblzma-dev \
            libpcre3-dev \
            build-essential

      - name: Set up renv
        run: |
          install.packages("renv")
          renv::restore(prompt = FALSE)
          renv::snapshot(prompt = FALSE)
        shell: Rscript {0}

      - name: Remove local renv library
        run: |
          unlink("renv", recursive = TRUE)
        shell: Rscript {0}

      - name: Install rsconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}

      - name: Authenticate with shinyapps.io
        run: |
          rsconnect::setAccountInfo(
            name   = Sys.getenv('SHINYAPPS_ACCOUNT'),
            token  = Sys.getenv('SHINYAPPS_TOKEN'),
            secret = Sys.getenv('SHINYAPPS_SECRET')
          )
        shell: Rscript {0}

      - name: Deploy app
        run: |
          rsconnect::deployApp(
            appDir  = '.',
            appName = 'shinymrp',
            server  = 'shinyapps.io',
            forceUpdate = TRUE
          )
        shell: Rscript {0}
