name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Publish to shinyapps.io
    runs-on: ubuntu-latest
    env:
      R_CONFIG_ACTIVE: shinyapps
      SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
      SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect

      - name: Authenticate with shinyapps.io
        run: |
          unlink("renv.lock")
          rsconnect::setAccountInfo(
            name   = Sys.getenv('SHINYAPPS_ACCOUNT'),
            token  = Sys.getenv('SHINYAPPS_TOKEN'),
            secret = Sys.getenv('SHINYAPPS_SECRET')
          )
        shell: Rscript {0}

      - name: Deploy app
        run: |
          rsconnect::deployApp(
            appDir  = '.',
            appName = 'shinymrp',
            server  = 'shinyapps.io',
            forceUpdate = TRUE
          )
        shell: Rscript {0}
